name: Hello World!

on:
  pull_request:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
